version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: vantage_postgres
    environment:
      POSTGRES_USER: vantage
      POSTGRES_PASSWORD: vantage_pass
      POSTGRES_DB: vantage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vantage"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vantage_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
